### ISSUE TITLE
enhancement: move i18n logic to frontend

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/bucketeer#1253]
Now, we have part of the i18n implementation on both sides, front and backend. Because the i18n implementation in all APIs made the backend code too hard to read, we decided to do this only on the front end.

**Comment by t-kikuc** [comment]
TODO: 

- [x] Refactor error structs in backend
- [ ] Update frontend
- [ ] Delete old i18 logics in backend

**Comment by t-kikuc** [comment]
revised TODO: 

- [ ] Refactor error structs in backend
    - [x] Define the new struct
    - [ ] delete all code depending on `localizer`
    - [ ] delete `localizer` itself (keep `locale` package including `locale.go`)
- [ ] Update frontend 
- [ ] Delete localizations in `DomainEvent` (migrations seem to be unnecessary)

**Comment by t-kikuc** [comment]
revised TODO: 

- [x] refine the RFC #2205
- [ ] backend:
    - [ ] copy message template files to frontend #2259
    - [ ] refine the error struct #2207
    - [ ] update old errors that use the localizer (so many files)
- [ ] frontend: 
    - [ ] step1. temporal way using `message`(see [the RFC](https://github.com/bucketeer-io/bucketeer/blob/main/docs/rfcs/move-i18n-logic-to-frontend.md#frontend-updates))
    - [ ] step2. complete way

**Comment by t-kikuc** [comment]
Completed!
