### ISSUE TITLE
feat: evaluate the user in the nodejs sdk to improve response latency

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/bucketeer#1260]
Go reference: https://github.com/bucketeer-io/bucketeer/issues/921

## Summary

The current architecture when the get variation interface is called. It requests the evaluation directly from the server.
This approach is more straightforward but may introduce latency. Also, this could lead to infra-cost issues because it could evaluate the same user many times in a short time, even if the flag didn't change.

We should consider implementing the evaluation logic in the SDK to implement a cache similar to the client SDK.
This would improve the latency issues and drastically reduce the requests to the server, reducing the infra-cost.

I was thinking of creating a new common repository for the evaluation and proto files, but it would be better if we kept this as a mono repo for this case. We can move it to another repository in the future if needed.

## TODO

- [x] Create the evaluation package in the main repo
- [x] Implement API to get all flags and segment users per environment using the server-side API key
- [x] Implement cache in the Nodejs SDK (In-memory)
- [x] Implement the configuration to select to evaluate locally or remotely
- [x] Update documentation
