### ISSUE TITLE
chore: add `IsSystemAdmin` field to `IDToken`

### ISSUE THREAD

**Issue by cre8ivejp** [bucketeer-io/bucketeer#774]
First, we must **update the service token secret** before proceeding.

#### TODO

- [x] Add the `IsSystemAdmin` field to `IDToken`
  - https://github.com/bucketeer-io/bucketeer/pull/776
- [x] Delete the `AdminRole` field
  - https://github.com/bucketeer-io/bucketeer/pull/791
  - https://github.com/bucketeer-io/bucketeer/pull/794
- [x] Delete the old [account proto message](https://github.com/bucketeer-io/bucketeer/blob/main/proto/account/account.proto#L24-L40)
  - https://github.com/bucketeer-io/bucketeer/pull/843

**Comment by kentakozuka** [comment]
done
